Repository RocketChat/Apps.Notion, pull requests merged in 2024-03, with the labels that each got.

#54 [Chore] Add changes to remove line breaks
  enum/CommandParam.ts
  enum/messages.ts
  src/authorization/OAuth2Client.ts
  src/helper/message.ts
  src/lib/BlockBuilder.ts
Labels: chore

#49 [Feat] Adds Change Workspace Menu in Create Page or Record Modal
  enum/modals/NotionDatabase.ts
  src/handlers/ExecuteBlockActionHandler.ts
  src/modals/createPageOrRecordModal.ts
Labels: enhancement

#53 [ Fix ] Title Input Visibility When Nothing is Selected in Select Page Dropdown
  src/handlers/ExecuteBlockActionHandler.ts
  src/modals/createPageOrRecordModal.ts
Labels: bug

#73 [Enhance] Improve readability of comment created time
  src/helper/getTimeAgoFromISO.ts
  src/lib/NotionSDK.ts
Labels: enhancement

#51 [Feat] Close window automatically upon success or unsuccess workspace connection
  enum/OAuth2.ts
  enum/messages.ts
  src/endpoints/webhook.ts
  src/helper/getAuthPageTemplate.ts
Labels: enhancement
